// Auto-generated from NEXUS Category Catalogue PDF (110 pages, 74 unique products across 17 categories).
// Each entry seeds the product catalog with real name/category/description/features/usage/presentation.
// Export-shipping fields (dimensions, units/package, NW/GW per package, CIF rate) are left as 0/blank —
// the catalog PDF doesn't specify carton packing, so these are filled in per-product when first used on an invoice.
module.exports = [
  {
    name: "Natu X Chol",
    category: "Natural (Herbal) Supplements",
    description: "Natu X Chol replaces synthetic choline chloride in a safe, effective, and affordable manner. Using a blend of Botanicals that are high in highly bioavailable choline, it was scientifically created.",
    features: ["For the best possible health and productivity, provides the ideal amount of choline.", "Keeps fatty liver syndrome under control and enhances energy metabolism.", "Keeps the yield and quality of the carcass intact.", "Preserves the vitamin content of premixes and feed.", "Enhances Health & living conditions"],
    usage_info: "FEED INCLUSION RATE:\nBroilers: 250 to 400 g/ ton of feed\nLayers: 150 to 300 g/ton of feed\nPigs: 100 to 400 g/ton of feed\nTurkeys: 200 to 400 g/ton of feed\nRuminants: 150 to 250 g/ton of feed",
    presentation: "25 KG",
    pack_size: "25 KG",
  },
  {
    name: "Natu X Chol DS",
    category: "Natural (Herbal) Supplements",
    description: "Natural Choline Supplement with Double Strength",
    features: ["Promotes optimal liver function", "Helps prevent fatty liver syndrome, perosis, and hepatic hypertrophy", "Improves hatchability and viability of birds", "Ensures optimal choline and biotin activity for overall health and productivity", "Supports growth, feed conversion (FC), and egg production"],
    usage_info: "FEED INCLUSION RATE:\nBroiler: 125 to 200 g/ton of feed\nLayers: 75 to 175 g/ton of feed\nPigs: 50 to 200 g/ton of feed\nSheep and Goats: 20 to 60 g/ton of feed\nCattle: 75 to 250 g/ton of feed",
    presentation: "25 KG",
    pack_size: "25 KG",
  },
  {
    name: "Natu X Lys",
    category: "Natural (Herbal) Supplements",
    description: "Natu X Lys is crafted from specially selected botanicals that offer high lysine activity, delivering lysine in conjugated dipeptide and oligopeptide forms.",
    features: ["Enhances body weight and feed conversion ratio (FCR)", "Maximizes egg production and egg weight", "Boosts hatchability and overall hatching performance", "Enhances protein synthesis and optimizes energy utilization", "Regulates fat metabolism, reducing the risk of fatty liver syndrome"],
    usage_info: "FEED INCLUSION RATE:\n1kg Natu X Lys can replace 1 kg of synthetic\nL-lysine or as per the directions of the\nnutritionist",
    presentation: "25 KG",
    pack_size: "25 KG",
  },
  {
    name: "CocciShield",
    category: "Natural (Herbal) Supplements",
    description: "COCCISHIELD is a harmonious blend of anti-coccidial phytochemical bioactives.",
    features: ["Provides effective protection against coccidiosis and other intestinal infections", "Also functions as an immunomodulator", "Supports optimal health, performance, and feed efficiency", "Assists in managing oxidative stress", "Promotes a healthy gut environment"],
    usage_info: "DOSE INTAKE LEVELS:\nPOWDER\nBroilers/Layers & Swine: 0.5 Kg to 1.5 kg\nper ton of feed\nOr as per the direction of the veterinarian.\nLIQUID\n1 ml to 5 ml per liter of drinking water\nOr as advised by Nutritionist / Veterinarian",
    presentation: "25 KG, 1 Liter",
    pack_size: "25 KG, 1 Liter",
  },
  {
    name: "Natu X D3",
    category: "Natural (Herbal) Supplements",
    description: "A natural origin of Calcitriol",
    features: ["Increases shell thickness, density, weight, and strength, reducing soft eggs and breakages in end layers", "Lowers egg breakage rates", "Enhances immunity", "Reduces flock mortality", "Prevents tibial dyschondroplasia", "Protects against field rickets and cage fatigue", "Calcitriol, as a natural source, is highly stable"],
    usage_info: "FEED INCLUSION RATE:\nLayers: 100 g/Ton of feed\nBroilers: 100 g/Ton of feed\nOr as advised by a Veterinarian or\nNutritionist\nThe product must be administered orally,\nmixed with the feed",
    presentation: "25 KG",
    pack_size: "25 KG",
  },
  {
    name: "StressZil-H",
    category: "Natural (Herbal) Supplements",
    description: "Natural solution to manage diarrhea and loose droppings in poultry & swine",
    features: ["Helps control diarrhea and loose droppings", "Supports optimal gut health", "Ensures food chain safety", "Promotes healthy growth", "Environmentally safe"],
    usage_info: "BENEFITS:\nFEED INCLUSION RATE:\nPoultry:\nFor Prevention: 1 kg per ton of feed\nFor control: 2-3 kg/ton of feed, depending\nupon severity, with or without antimicrobials\ndepending upon type of diarrhea\nSwine:\nFor healthy gut function & prevention of\ndiarrhea: 1.5 kg per ton of feed\nFor disturbed gut function & control of\ndiarrhea: 2-3 kg per ton of feed\n(or) as advised by a veterinarian",
    presentation: "25 KG",
    pack_size: "25 KG",
  },
  {
    name: "YolkNex Yellow",
    category: "Natural (Herbal) Supplements",
    description: "A plant-based additive for enhanced yolk color and improved egg quality",
    features: ["Enhances egg yolk color", "Improves metabolic efficiency", "Helps extend egg shelf life", "Promotes skin pigmentation", "Contributes to superior meat quality", "Supports overall bird health"],
    usage_info: "BENEFITS:\nDOSEGE:\n180 to 200 g/ton of feed for color fan value of 5\n550 to 600 g/ton of feed for color fan value of 7\nProduct can be directly blended with the feed\nIt is important to mix the product with the\nfeed at the time of feeding\nOnce the product is opened, it should be\nfinished within 48 hours of time or kept in\nappropriate storage conditions for the\nbest results",
    presentation: "25 KG",
    pack_size: "25 KG",
  },
  {
    name: "YolkNex Plus",
    category: "Natural (Herbal) Supplements",
    description: "A plant-based additive for enhanced yolk color and improved egg quality",
    features: ["Enhances egg yolk pigmentation", "Supports overall bird health", "Improves metabolic activity", "Helps extend egg shelf life", "Promotes skin pigmentation", "Contributes to improved meat quality"],
    usage_info: "BENEFITS:\nDOSAGE:\n300 g to 350 g/ton of feed for achieving a\nRoche color fan value of 10-12\nThe product should be mixed with the feed\nat the time of feeding\nOnce the product is opened, it should be\nfinished within 48 hours of time or kept in\nappropriate storage conditions for the\nbest results",
    presentation: "25 KG",
    pack_size: "25 KG",
  },
  {
    name: "YolkNex Ultra",
    category: "Natural (Herbal) Supplements",
    description: "A plant-based additive for enhanced yolk color and improved egg quality",
    features: ["Enhances egg yolk pigmentation", "Supports overall bird health", "Improves metabolic activity", "Helps extend egg shelf life", "Promotes skin pigmentation", "Contributes to improved meat quality"],
    usage_info: "BENEFITS:\nDOSEGE:\n200 g to 500 g per ton of feed according to the\nyolk color desire ranging from 8 to 14 and feed\ncomposition or as advised by Nutritionist\nThe product should be mixed with the feed at\nthe time of feeding\nOnce the product is opened, it should be\nfinished within 48 hours or stored in\nappropriate storage conditions for the\nbest results",
    presentation: "25 KG",
    pack_size: "25 KG",
  },
  {
    name: "Natu X C",
    category: "Natural (Herbal) Supplements",
    description: "Natu X C is a natural plant-derived source of Vitamin C combined with Bioflavonoids. It substitutes synthetic Vitamin C with a more stable organic form, offering greater heat resistance. Additionally, it supplies crucial elements to support the body during stress.",
    features: ["Enhances production parameters, including weight in broilers and shell quality in layers", "Aids in maintaining homeostasis by regulating body temperature and promoting corticosteroid secretion", "Functions as an antioxidant, reducing tissue damage caused by free radicals and toxins", "Boosts humoral and cell-mediated immunity impaired by stress, lowering the heterocyte-to- lymphocyte ratio under heat stress conditions"],
    usage_info: ":\nFEED INCLUSION RATE:\nBroilers/Layers /Swine: 100 gm per Ton of\nprepared feed (100 gm of NATU X C can be\nused in place of 100 gm synthetic vitamin C)",
    presentation: "25 KG",
    pack_size: "25 KG",
  },
  {
    name: "Natu X Met",
    category: "Natural (Herbal) Supplements",
    description: "Natu X Met is a natural source of active Methionine, scientifically formulated from a unique blend of botanicals. It contains Methionine in dipeptide and oligopeptide forms, offering a highly digestible composition.",
    features: ["Enhances protein and energy utilization efficiency", "Increases feed intake and improves feed conversion ratio (FCR)", "Promotes better live weight gain", "Significantly reduces liver triglyceride levels, helping to prevent fatty liver"],
    usage_info: ":\nFEED INCLUSION RATE:\n1 kg Natu X Met can replace 1 kg of\nsynthetic DL-Methionine or as per the\nadvice of the nutritionist.",
    presentation: "25 KG",
    pack_size: "25 KG",
  },
  {
    name: "Natu X Garli",
    category: "Natural (Herbal) Supplements",
    description: "Garlic Oil Extract (Allicin)",
    features: ["Natu X Garli exhibits a broad-spectrum antibacterial, antiviral, antifungal, and bactericidal effect", "It enhances appetite, increases feed intake, and improves survival rates, egg production, hatchability in breeders, and overall performance in chickens", "Natu X Garli enhances the flavor of meat and helps lower cholesterol levels", "It demonstrates a strong antifungal effect against various fungi, including Aspergillus flavus, Aspergillus niger, and Aspergillus fumigatus, effectively preventing moldy feed and extending its shelf life", "Natu X Garli is free from side effects, residue, and resistance", "There is no cross-resistance with other in-feed antibiotics or feed ingredients"],
    usage_info: ":\nDOSE INTAKE LEVELS\nLIQUID:\nPoultry: 1 ml per 5 liters of drinking water for 5-7 days\nDairy Cattle: 5-10 ml daily for 3-5 days.\nFor Spray as disinfectant (in presence of birds): 3 to 5 ml\nper liter of water.\nPOWDER:\nCow, Swine",
    presentation: "25 KG, 1 Liter",
    pack_size: "25 KG, 1 Liter",
  },
  {
    name: "CurcuMax",
    category: "Natural (Herbal) Supplements",
    description: "Curcumin powder, oil & water soluble liquid as natural growth promoter",
    features: ["Acts as an immunity booster, enhances digestibility, improves feed palatability, and provides anti-inflammatory support", "Enhances feed color", "Helps maintain and preserve feed quality", "Exhibits antifungal, antibacterial, and antiviral properties"],
    usage_info: "BENEFITS:\nDOSAGE:\nPowder & Oil:\n500 g to 1 kg per ton of feed\nAdd the recommended quantity of CurcuMax\nin 5-6 kg of compounded feed and add the\nresulting mixture in the finished feed.\nLiquid:\nFor prevention of disease & immunity:\n200 ml to 300 ml/1000 liter of drinking water\nIn case of Disease Outbreak: 300 ml to\n500 ml per 1000 Liter of Drinking Water\nFeed Inclusion: 250 ml to 500 ml per ton of feed",
    presentation: "25 Kg, 1 Liter",
    pack_size: "25 Kg, 1 Liter",
  },
  {
    name: "Natu X Pclean",
    category: "Natural (Herbal) Supplements",
    description: "CLEANING OF ECTOPARASITES",
    features: [],
    usage_info: "MODE OF ACTION:\nNatu X PClean Spray primarily targets the\nganglia of the central nervous system,\nenhancing nerve function by prolonging\nthe permeability of saliva during the\nrecovery phase of neuronal action potential.\nIt induces a rapid paralytic effect on insects,\ninitially causing muscular excitation and\nconvulsions.\nADMINISTRATION:\nSpray on affected part as per guidance\nof veterinarian.",
    presentation: "100 ml",
    pack_size: "100 ml",
  },
  {
    name: "Natu X Liv",
    category: "Natural (Herbal) Supplements",
    description: "Natu X Liv is enriched with potent botanical bioactives that serve as hepatoprotective, hepatoregenerative, and hepatostimulatory agents.",
    features: ["To promote optimal liver function", "For addressing anorexia caused by hepatic disorders", "To support liver health during dysfunction", "After de-worming and antibiotic treatments", "To enhance digestibility and feed conversion ratio (FCR)"],
    usage_info: "DOSE INTAKE LEVELS:\nTo be mixed with feed for ruminants OR\nalong with water for Poultry Via oral route\nonce in a day\nLIQUID:\nPoultry: 1 liter per 2000 litres of drinking water\nCattle/Horses: 30-40 ml\nHeifer & Calves: 15-20 ml\nSheep & Goats: 7-10 ml\nPOWDER:\nPoultry & Swine: 250 g per ton of feed\nor as advised by nutritionist/Veterinarian",
    presentation: "25 KG, 1 Liter",
    pack_size: "25 KG, 1 Liter",
  },
  {
    name: "Natu X Resp",
    category: "Natural (Herbal) Supplements",
    description: "Natu X Resp is a water-soluble concentrate derived from essential oils of botanical origin, offering functional benefits as bronchodilators and expectorants.",
    features: ["Aids in the optimal functioning of the entire respiratory system", "Provides quick relief from respiratory issues in birds", "Supports respiratory wellness in birds, especially during challenges such as CRD, Coryza, and other common respiratory conditions.", "Promotes relaxation in birds, allowing them to consume a normal amount of feed and achieve expected results"],
    usage_info: "DOSE INTAKE LEVELS:\nIN BIRDS:\nDrinking Water Application:\n500 ml to 1500 ml per 1,000 litres of drinking\nwater\nNebulizer Application: 1000 ml per 1000 litre\nof drinking water\nSwine: 500 ml to 750 ml per 1000 litres of\ndrinking water\nOr as advised by Nutritionist/Veterinarian",
    presentation: "5 Liter, 1 Liter",
    pack_size: "5 Liter, 1 Liter",
  },
  {
    name: "Natu X Resp +",
    category: "Natural (Herbal) Supplements",
    description: "Natu X Resp+ is a 5X water soluble concentrate based on essential oils of botanical origin having functional properties as Bronchodilator and Expectorant",
    features: ["Birds relaxes from respiratory troubles quickly", "Improves function of Respiratory troubles quickly", "Supports respiratory wellness in birds, especially during challenges such as CRD, Coryza, and other common respiratory conditions.", "Helps in functioning of total respiratory organs with its full capacity", "Bird relaxes well and takes normal quantity of feed to produce normal results"],
    usage_info: "DOSE INTAKE LEVELS:\n1 ml per 5 liters of water for 3 to 5 days",
    presentation: "1 Liter",
    pack_size: "1 Liter",
  },
  {
    name: "VitaNex Forte",
    category: "Vitamin Supplements",
    description: "GROWTH PROMOTER, MILK YIELD ENHANCER, EGG PRODUCTION ENHANCER AND FERTILITY IMPROVER",
    features: ["Enhances reproductive performance", "Stimulates immunity", "Acts as an anti-stress agent during animal transport and illness", "Addresses vitamin deficiencies", "Increases milk production", "Improves egg production and hatchability", "Promotes growth"],
    usage_info: "DOSE INTAKE LEVELS:\nPoultry and Swine: 1 ml per 4 litres of\ndrinking water for 3 - 5 days.\nCalves, Goats and Sheep: 1 ml per 40 kg\nbody weight for 3 - 5 days.\nCattle: 1 ml per 80 kg body weight for\n3 - 5 days.\nOr as recommended by Nutritionist/\nVeterinarian",
    presentation: "1 Liter",
    pack_size: "1 Liter",
  },
  {
    name: "VitaNex Bolus",
    category: "Vitamin Supplements",
    description: "Appetite Replenishment Bolus",
    features: ["Particularly beneficial during the fattening phase and for enhancing fertility", "Complements antiparasitic treatments", "Prevents and treats deficiencies and sub-deficiencies in vitamins and trace elements", "Suitable for Cattle, Camelids, Small Ruminants, and Pigs"],
    usage_info: ":\nDOSE INTAKE LEVELS:\nOral route (for 5-day)\nCamels: 2 boli\nCattle, Pigs: 1 bolus\nCalves, Sheep, Goats: \u00bd bolus",
    presentation: "10 x 5 Boli",
    pack_size: "10 x 5 Boli",
  },
  {
    name: "VitaNex B",
    category: "Vitamin Supplements",
    description: "Vitamins are essential for the proper operation of many physiological functions. Vitanex B is a liquid feed supplement containing Vitamin B Complex",
    features: ["Supplementation of minerals for better growth", "Maintenance and better milk production in Cattle", "Better weight gain in Sheep and Calves"],
    usage_info: ":\nDOSE INTAKE LEVELS:\nTo be mixed in drinking water\nCattle/Poultry/Sheep/Goats/Horses:\n100 ml per 100 litres of drinking water\nOr as recommended by Nutritionist/\nVeterinarian",
    presentation: "1 Liter",
    pack_size: "1 Liter",
  },
  {
    name: "VitaNex Forte Powder",
    category: "Vitamin Supplements",
    description: "Water Soluble Powder product containing Vitamins, Trace Mineral Elements and Amino Acids",
    features: ["Ensures rapid growth in Poultry and Ruminants", "Prevents stress due to animal transport and cold and heat, in all types of animals", "Prevents anemia and weakness due to infectious and parasitic diseases", "Prevents nutritional deficiencies in all types of animals", "Improves muscle and nervous disorders", "Improves egg production", "Improves hatchability", "Improves feed conversion rate (FCR)"],
    usage_info: ":\nFEED INCLUSION RATE:\nFor oral administration via\ndrinking water\nDietary Supplement:\n1 g/10 litres/day\nPerformance Deficiencies:\n1 g/5 litres/day\nOr as recommended by\nnutritionist/veterinarian",
    presentation: "1 Kg, 100 g",
    pack_size: "1 Kg, 100 g",
  },
  {
    name: "VitaNex E+Se Plus",
    category: "Vitamin Supplements",
    description: "Liquid supplementation of VITAMIN E FORTIFIED WITH SELENIUM",
    features: ["Enhances vaccination titres for ND and IBD", "Reduces mortality caused by stress conditions", "Aids in quicker recovery from diseases", "Improves weight of the bursa, spleen, and thymus, boosting immunity", "Minimizes the occurrence of ascites and sudden death syndrome in broilers", "Supports optimal fertility in livestock and hatchability in breeder flocks", "Lowers transportation costs"],
    usage_info: ":\nDOSE INTAKE LEVELS:\nPoultry and Swine: 1 litre per 4000 litres\nof drinking water for 3 - 5 days\nCalves, Goats and Sheep: 1 ml per 40 kg\nbody weight for 3 - 5 days\nCattle: 1 ml per 80 kg body weight for\n3 - 5 days",
    presentation: "1 Liter",
    pack_size: "1 Liter",
  },
  {
    name: "VitaNex ADE Plus",
    category: "Vitamin Supplements",
    description: "VITANEX ADE Plus is specifically designed to meet the needs of Vitamins A, D3, E during stressful conditions. The precise combination of these vitamins effectively helps alleviate various types of stress.",
    features: ["It prevents & relieves all types of stress conditions leading to improved production performance", "Helps improve body resistance against infections", "Ensures optimal calcium levels and phosphorus in serum"],
    usage_info: ":\nDOSE INTAKE LEVELS:\nCalves, Goats and Sheep: 1 ml per 40 kg\nbody weight for 3 - 5 days\nCattle: 1 ml per 80 kg body weight for\n3 - 5 days\nPoultry and Swine: 1 litre per 4000 litres\nof drinking water for 3 - 5 days",
    presentation: "1 Liter",
    pack_size: "1 Liter",
  },
  {
    name: "ProbioNex Boost",
    category: "Probiotics",
    description: "Non Medicinal Multi-Strain Water Soluble Probiotic Feed Additive",
    features: ["Promotes growth", "Improves feed conversion rate", "Reduces diarrhea and stress", "Decreases Stink", "Improves health during disease conditions", "Supports the establishment of beneficial gut microflora", "Lowers mortality when used alongside toxin binders in mycotoxicosis cases"],
    usage_info: ":\nFEED INCLUSION RATE:\nPoultry: 1 gm per liter of drinking\nwater\nPigs/Sheep/Goats: 2.5 to 5 g per\nanimal per day\nCattle: 5 to 10 g per animal per day",
    presentation: "1 Kg, 100 g",
    pack_size: "1 Kg, 100 g",
  },
  {
    name: "PhyNex",
    category: "Enzymes",
    description: "feed grade phytase enzyme",
    features: ["Nutrient values for phytase, phosphorus, calcium, amino acids, and energy-producing dietary components can be utilized in broiler diet formulation from batch to slaughter without adversely affecting growth performance, carcass characteristics, or meat quality.", "Phytase plays a key role in lowering diet costs by reducing the need for di-calcium phosphate (DCP). Its inclusion enhances growth performance in young chickens. Studies suggest that the increase in feed intake may be attributed to a longer feed transit time (from ingestion to excretion) in chickens consuming Phytase-based diets. Additionally, Phytase supplementation boosts the availability of essential trace minerals such as copper, iron, manganese, and zinc.", "PHYNEX is a highly potent Phytase enzyme specifically formulated to release phosphorus. Derived from a thermostable organism, PHYNEX can endure pelleting temperatures. It has also been shown to improve egg shell quality and feed conversion ratio (FCR)."],
    usage_info: ":\nFEED INCLUSION RATE:\nVia oral route. Add the recommended quantity of\nPhytase in the 5-6 kg of compounded feed and add\nthe resulting mixture in the finished feed.\nBroilers: 100 gm per ton of feed\nLayers & Breeders: 60 gm per ton of feed\nSwine: 100 gm per ton of feed\nOR\nPoultry & Swine: 12.5 g/Kg of Dicalcium Phosphate\nto be replaced, with due correction of calcium",
    presentation: "25 KG",
    pack_size: "25 KG",
  },
  {
    name: "NexEnzy",
    category: "Enzymes",
    description: "Balanced enzyme premix for poultry Feeds",
    features: ["Enhances nutrient utilization", "Optimizes growth and production", "Reduces the need for DCP", "Prevents wet litter conditions", "Minimizes the impact of anti-nutritional factors"],
    usage_info: ":\nDOSE INTAKE LEVELS:\nPOWDER\n500 g per ton of feed for Poultry\nLIQUID\nChick: 5 ml daily\nGrower/Finisher: 15-20 ml per\n100 birds\nLayers: 20 ml per 100 birds",
    presentation: "25 KG, 1 Liter",
    pack_size: "25 KG, 1 Liter",
  },
  {
    name: "ProteaNex",
    category: "Enzymes",
    description: "Feed grade Thermostable Protease enzyme",
    features: ["Enhances amino acid digestion consistently, leading to better nutrient utilization", "Works synergistically with naturally occurring proteases, significantly increasing peptide availability and thereby improving overall animal performance", "Improves the digestibility of diverse protein sources and cereals, enabling feed formulation flexibility and potential reductions in feed cost"],
    usage_info: "BENEFITS:\nDOSAGE:\nPoultry & Swine: 150-200 g/MT\nOr as recommended by Nutritionist\nor Veterinarian",
    presentation: "25 KG",
    pack_size: "25 KG",
  },
  {
    name: "SugraNex",
    category: "Flavours and Sweeteners",
    description: "Sweet Taste Enhancer for Cattle/Swine Feed & Formulation Application",
    features: ["A potent sweetener for enhancing the taste of animal feed.", "Classified as a sweetening palatant according to EU feed additive standards.", "Approximately 550 times sweeter than sugar; 1 kg equals 550 kg of sugar.", "Contains prebiotics, promoting the growth of beneficial gut microflora.", "A synergistic mix of high-intensity sweeteners, taste enhancers, and potentiators.", "All ingredients are listed by both the USFDA and EU for human food and animal feed use.", "Free from animal-derived by-products.", "Delivers a pleasant, long-lasting sweet taste without any bitter or metallic aftertaste.", "Masks bitter flavors from medications and minerals in feed.", "Increases the palatability of feed or mineral blends, encouraging higher consumption.", "Requires low inclusion rates, offering flexibility for incorporating less palatable but nutritious ingredients, such as Guar Korma."],
    usage_info: "FEED INCLUSION RATE:\nIN FEED\n100 to 200 grams per ton of Compounded Finished Feed\n200 to 400 grams per ton of Mineral mixture\nIN SPECIES\nSwine: 50-150 g/ton of feed\nRuminants: 100-250 g/ton of feed\nOr as suggested by Animal Nutritionist",
    presentation: "25 KG",
    pack_size: "25 KG",
  },
  {
    name: "Nexus Molasses, Nexus Green Grass, Nexus Lacto-Vanilla, Nexus Banana Flavors",
    category: "Flavours and Sweeteners",
    description: "feed flavoring for ruminants feed application",
    features: ["Promote animal feed intake and then gain overall nutrition and grow quickly.", "Masking of strong odours and pungent non-palatable essential feed additives, allows flexibility of ingredient incorporation to save feed cost.", "Improves feed consumption and recovery of diseased animals."],
    usage_info: ":\nFEED INCLUSION RATE:\n400 g per ton of feed including Milk\nreplacers, Mineral mixtures, Cattle feed\nsupplements, compounded or\nconcentrated feeds\nOR as suggested by the Veterinarian/\nNutritionist.",
    presentation: "25 Kg",
    pack_size: "25 Kg",
  },
  {
    name: "ProteiNex",
    category: "Nutritional Supplements",
    description: "WATER SOLUBLE AMINO ACID POWDER",
    features: ["ProteiNeX is a carefully formulated blend of essential amino acids for Calves, Cattle, Goats, Poultry, Sheep, and Swine.", "It supports the prevention or treatment of amino acid deficiencies in farm animals.", "It aids in preventing or managing stress caused by factors such as vaccination, disease, transportation, high humidity, extreme temperatures, or sudden temperature fluctuations.", "It enhances feed conversion efficiency."],
    usage_info: ":\nFEED INCLUSION RATE:\nFor oral administration\nPoultry and Swine: 1 Kg per 4000 liters\nof drinking water for 3-5 days\nCalves, Goats, Sheep: 1 g per 40 kg body\nweight for 3-5 days\nCattle: 1 g per 80 kg body weight for\n3-5 days",
    presentation: "1 Kg",
    pack_size: "1 Kg",
  },
  {
    name: "Ferro X Boost",
    category: "Nutritional Supplements",
    description: "Rich Hematinic Supplement",
    features: ["Indicated for anemia in Piglets and Swine", "Assists in hemoglobin formation, alleviating anemic conditions", "Provides immediate energy for enhanced performance", "Helps control CIA, GD, IBD, ND, and NE", "Reduces stress and boosts overall performance", "Promotes weight gain and improves feed conversion ratio (FCR)", "Enhances egg quality", "Reduces metabolic issues such as ascites and SDS", "Pharma-grade quality product for optimal results"],
    usage_info: ":\nDOSE INTAKE LEVELS:\nPoultry/Swine: 1 ml per litre of drinking water\nCattle: 30 ml orally daily\nSheep/Goat: 10 ml orally daily\nOr as advised by Nutritionist/Veterinarian\nAdd Ferro X Boost in a bucket of water (1:4).\nMix thoroughly the content.\nTransfer the mix content in in empty jar/\nbucket and repeat the process 3-4 times",
    presentation: "5 Liter, 1 Liter",
    pack_size: "5 Liter, 1 Liter",
  },
  {
    name: "CalciNex P",
    category: "Nutritional Supplements",
    description: "CALCINEX P is a nutritional feed supplement to maximize growth & production",
    features: ["Aids in musculoskeletal growth in Poultry", "Prevents deficiencies in calcium and phosphorus", "Enhances nutrient utilization by improving digestion and absorption", "Improves feed conversion ratio (FCR) for better growth performance"],
    usage_info: ":\nDOSE INTAKE LEVELS:\nPoultry: 1-2 ml per liter of\ndrinking water for 7-10 days\nCattle: 50 ml daily\nor as advised by Nutritionist/Veterinarian",
    presentation: "5 Liter, 1 Liter",
    pack_size: "5 Liter, 1 Liter",
  },
  {
    name: "CalciNex Plus",
    category: "Nutritional Supplements",
    description: "CALCINEX PLUS Liquid Concentrate is a premium, highly concentrated feed supplement rich in Calcium and Phosphorus, enhanced with essential vitamins. It boosts both the quality and quantity of milk while effectively preventing milk fever.",
    features: ["Enhances milk production", "Promotes better growth in young Calves", "Supports optimal fetal development in pregnant cows and buffaloes"],
    usage_info: ":\nDOSE INTAKE LEVELS:\nVia Oral route once in a day\nCow and Buffalo: 100 ml once in a day, orally\nSheep and Goat: 10 ml once in a day, orally\nCalves: 40 ml once in a day, orally",
    presentation: "1 Liter",
    pack_size: "1 Liter",
  },
  {
    name: "CalciNex Gold",
    category: "Nutritional Supplements",
    description: "CALCINEX GOLD is a premium, high-concentration liquid feed supplement, providing chelated oral calcium enriched with a potent combination of calcium, phosphorus, vitamin D3, and vitamin B12. It enhances both the quality and quantity of milk while helping to prevent milk fever.",
    features: ["Enhances milk production", "Supports optimal growth in young Calves", "Promotes healthy fetal development in pregnant cows and buffalo", "Delivers immediate energy to high-yielding animals"],
    usage_info: ":\nDOSE INTAKE LEVELS:\nOnce in a day\nCow and Buffalo: 50 ml daily, orally\nHigh Yielders: 100 ml daily, orally\nSheep and Goat: 5 ml daily, orally\nCalves: 20 ml daily, orally",
    presentation: "5 Liter, 1 Liter",
    pack_size: "5 Liter, 1 Liter",
  },
  {
    name: "CalciNex Gel",
    category: "Nutritional Supplements",
    description: "Highly Bioavailable oral anionic Calcium Gel",
    features: ["Helps prevent milk fever", "Stimulates Vitamin D3 activation and calcium metabolism", "Serves as a follow-up therapy after IV calcium infusion", "Improves uterine tone, promoting better consumption", "Maintains serum calcium levels for a longer duration compared to IV calcium therapy", "Delivers five times more calcium than an IV calcium injection"],
    usage_info: ":\nDOSE INTAKE LEVELS:\nVia Oral route\nAdminister one tube 6-12 hours prior to\ncalving and give another tube within\n6-12 hours after calving.",
    presentation: "300 g",
    pack_size: "300 g",
  },
  {
    name: "MinzNex",
    category: "Nutritional Supplements",
    description: "MINZNEX is a mineral mixture with essential amino acids for better appetite, growth and productivity",
    features: ["Providing minerals to support optimal growth in animals", "Nutritional support for overall health", "Essential amino acids required for the proper development of animals"],
    usage_info: ":\nFEED INCLUSION RATE:\nMixed with Drinking Water as follow:\nCow, Camel: 50 g/20L/head/daily\nCalves, Sheep, Goat: 25-30 g/10L/head/\ndaily\nPoultry: 2-4 g/litre of drinking water",
    presentation: "10 x 1 KG",
    pack_size: "10 x 1 KG",
  },
  {
    name: "MinzNex Gold",
    category: "Nutritional Supplements",
    description: "MINZNEX GOLD is a metho-chelated mineral mixture and vitamins for cattle feeding",
    features: ["Mineral supplementation for enhanced growth", "Supports maintenance and improves milk production in Cattle", "Promotes better weight gain in Sheep and Calves"],
    usage_info: ":\nFEED INCLUSION RATE:\nVia Oral route and to be mixed\nwith feed\nCow and Buffalo: 50 g per day for\nmaintenance and better milk\nproduction\nCalf/Sheep: 25 g - 30 g per day for\nbetter weight gain\nHorse: 50 g per day\nMixing Ratio: 1 kg - 2 kg to be mixed\nin 100 kg feed",
    presentation: "10 Kg",
    pack_size: "10 Kg",
  },
  {
    name: "Stress Zil",
    category: "Nutritional Supplements",
    description: "Extracts | Energy | Electrolytes | Amino acids | Vitamins",
    features: ["Enhances the immune system", "Boosts overall animal health", "Provides sustained energy", "Rich source of amino acids", "Supports increased egg production", "Promotes higher milk yield", "Facilitates faster growth in Broiler Chickens and fattening animals", "Aids in weight gain for Broiler Chickens and fattening animals", "Stimulates metabolism", "Encourages improved appetite"],
    usage_info: ":\nDOSE INTAKE LEVELS:\nCows: 15-20 ml per animal/day\nSheep,Goats: 10 ml per animal/day\nLambs and Kids: 5 ml per animal/day\nCalves: 10 ml / day\nPoultry: 1000 ml per 1000 liters of water",
    presentation: "1 Liter",
    pack_size: "1 Liter",
  },
  {
    name: "ViruZil",
    category: "Disinfectants",
    description: "VIRUZIL is a disinfectant possessing wide spectrum virucidal, Bactericidal and fungicidal activity. The effectiveness of VIRUZIL if further enhanced by its excellent detergent properties, so that clean disease-free surfaces can be achieved.",
    features: [],
    usage_info: "MODE OF ACTION:\nVIRUZIL breaks down sulfur bonds in proteins and\nenzymes, interfering with the cell membrane's\nfunction and leading to the rupture of the cell wall.\nBROAD SPECTRUM DISINFECTANT:\nVIRUZIL is effective against a wide range of\nmicroorganisms that impact animals, including\nviruses, gram-positive and gram-negative\nbacteria, fungi, molds, yeasts, and mycoplasma.\nINSTRUCTIONS FOR THE DISINFECTION OF PREMISES AND LIVESTOCK EQUIPMENT:\nSurface & Equipment Hygiene (disinfection)\n1:100 (10 g/litre of water)\nContinous Water System Hygiene\n1:1000 (1 g/liter of water)\nMisting/Aerial Spray Hygiene\n1:200 (5 g/liter of water)\nFootbaths: Changing the ViruZil disinfectant solution at 1% every 5 days or as soon\nas the color disappears yellow (Yellow colored indicator indicating the effectiveness\nof disinfectant).\nINSTRUCTIONS FOR AQUACULTURE/PICICULTURE:\nHatchery (Shrimp/Fish)\n5 g to 10 g/ton of water\nPond (Shrimp/Fish)\n500 g to 2 kg/ha\nTreatment unit (water washing and sanitation)\nup to 5 g to 10 g/ton of water",
    presentation: "1 KG",
    pack_size: "1 KG",
  },
  {
    name: "ToxZil P",
    category: "Toxin Binder",
    description: "Mycotoxin Risk Management Solution",
    features: ["TOXZIL P effectively adsorbs, retains, and eliminates mycotoxins through feces, inhibiting mold growth. It maximizes feed conversion ratio (FCR) while minimizing mortality, leading to enhanced productivity.", "Its cost-effectiveness makes it a valuable addition, as it is uniformly blended to mitigate the harmful effects of mycotoxins."],
    usage_info: "FEED INCLUSION RATE:\nRecommended at the rate of 1 to 2 Kg per\ntonne of feed depending upon moisture\nlevels\nOR as suggested by your nutritionist",
    presentation: "25 KG",
    pack_size: "25 KG",
  },
  {
    name: "ToxZil",
    category: "Toxin Binder",
    description: "TOXZIL is a feed ingredient that addresses the contamination of raw materials and finished feeds by various molds and mycotoxins, which can reduce the feed's quality and palatability. Mycotoxins are chemicals produced by specific fungi when they thrive in favorable conditions.",
    features: ["Enhances feed conversion ratio (FCR)", "Boosts productivity", "Cost-effective solution", "TOXZIL is thoroughly blended to counteract the harmful effects of mycotoxins."],
    usage_info: "Toxin Binders are designed to neutralize\nand bind mycotoxins, inhibiting mold growth.\nFEED INCLUSION RATE:\nPowder:\nMoisture content upto 15% (in normal season):\n1.5 to 2 kg per tonne of feed\nMoisture content above 15% (in rainy season):\n2.5 to 3 kg. per tonne of feed\nLiquid:\nPoultry: 1 ml per 3 to 5 litres of drinking water\nfor 4 to 6 days\nOr as recommended by Nutritionist/Veterinarian",
    presentation: "25 Kg, 1 Liter",
    pack_size: "25 Kg, 1 Liter",
  },
  {
    name: "ToxZil M",
    category: "Toxin Binder",
    description: "TOXZIL M is a versatile, broad-spectrum mycotoxin binder formulated to capture toxins in feed, safeguarding animals from their harmful effects.",
    features: ["Effectively binds various mycotoxins in feed, including aflatoxins, ochratoxins, trichothecenes, and more. Inhibits the growth of molds and bacteria, reducing the subsequent production of mycotoxins.", "Supports the body's natural immune defenses, helping to prevent mycotoxin-induced immunosuppression.", "Selectively targets mycotoxins while preserving vitamins, minerals, and other essential nutrients.", "Enhances animal performance and productivity.", "Easily flows and mixes uniformly into feed."],
    usage_info: "FEED INCLUSION RATE:\nTOXZIL M is recommended at the rate of 1 to 2 Kg\nper ton of feed depending upon moisture levels\nOR  as suggested by your nutritionist",
    presentation: "25 KG",
    pack_size: "25 KG",
  },
  {
    name: "FUNGINIL",
    category: "Toxin Binder",
    description: "FUNGINIL is a fungus, yeast, and spore inhibitor used in the production of balanced animal feed.",
    features: ["FUNGINIL is an essential additive in the manufacture of animal feed.", "It protects against fungal contamination throughout production, transportation and storage processes.", "Extends the storage life of food.", "Preserves the nutritional properties of food.", "It reduces the appearance of secondary toxic metabolites, called mycotoxins, responsible for the deterioration of the immune system of animals.", "FUNGINIL has a degradation temperature above 100\u00b0C, making it an excellent alternative for protecting pelleted, extruded and expanded foods, without evaporation or steam drag losses.", "FUNGINIL is compatible with all ingredients used to manufacture balanced animal feed."],
    usage_info: "DOSAGE:\nUse Funginil in relation to the moisture content\nof raw materials & finishes foods according to\nthe following table:\nHumidity (%)\nFunginil (kg/TM)\n12-14\n1.00\n14-16\n1.25\n>16\n1.50",
    presentation: "25 KG",
    pack_size: "25 KG",
  },
  {
    name: "FeedoNex Forte",
    category: "Acidifier",
    description: "Effective Potent Acidifier",
    features: ["Enhances feed conversion ratio", "Cost-efficient, contributing to feed savings", "Non-toxic and non-corrosive", "No withdrawal period required", "100% biodegradable and environmentally friendly", "Easy to handle and user-friendly", "Supports beneficial microflora and promotes the proliferation and maturation of intestinal cells"],
    usage_info: "DOSE INTAKE LEVELS:\nRegular use in feed: 500 g - 1 kg/ton of\nfinished feed\nLIQUID\nPoultry: 1 ml per 1 to 2 litre of drinking water\nfor 5 to 7 days\nOr as recommended by Nutritionist/\nVeterinarian",
    presentation: "25 KG, 1 Liter",
    pack_size: "25 KG, 1 Liter",
  },
  {
    name: "LeciNex",
    category: "Emulsifier",
    description: "POWDER FEED EMULSIFIER  FOR POULTRY AND PIGS",
    features: ["Enhances the absorption of nutrients from the gut", "Improves feed conversion ratio and overall performance", "Optimizes the bioavailability of both fat-soluble and water-soluble nutrients", "Aids in the efficient digestion of fat, maximizing energy utilization", "Prevents fat build-up and reduces abdominal fat", "Helps extract maximum nutritional value from high-density rations", "Minimizes fat/oil wastage due to indigestion", "Stimulates and supports the function of the liver, pancreas, bile ducts, and small intestine, enhancing enzymatic digestion of feed"],
    usage_info: "FEED INCLUSION RATE:\nPoultry: 200 to 500 g/ton of feed\nSwine: 500 g/ton of feed\nOr as recommended by Nutritionist/\nVeterinarian",
    presentation: "25 KG",
    pack_size: "25 KG",
  },
  {
    name: "Hepaxel",
    category: "Liver Tonic",
    description: "Liver expert for animal",
    features: ["Supports liver health", "Protects against the harmful effects of toxins", "Aids in managing fatty liver conditions", "Acts as a supplementary aid alongside antibiotic treatment", "Addresses nutritional deficiencies"],
    usage_info: ":\nDOSE INTAKE LEVELS:\nPoultry: 1\nto\n2 ml per litre per day in\ndrinking water\nCattle: 20 to 30 ml/day for 7 to 10 days\nSheep, Goat: 3 to 5 ml /day for\n7 to 10 days\nSwine:\n5 to 10 ml/day for 7 to 10 days",
    presentation: "5 Liter, 1Liter",
    pack_size: "5 Liter, 1Liter",
  },
  {
    name: "ElectroNex",
    category: "Electrolytes",
    description: "Water Soluble essential electrolytes with Vitamin C and Probiotics",
    features: ["Helps regulate body temperature and supports homeostasis through corticosteroid secretion", "Prevents dehydration and reduces mortality caused by heat stress", "Provides an immediate source of energy, maintaining performance and production", "Enhances immunity, improving both humoral and cell-mediated responses under heat stress", "Supports intestinal microflora that may be depleted due to heat stress", "Maintains calcium and magnesium levels, crucial for proper egg shell formation", "Improves the heterocyte-to-lymphocyte ratio, addressing stress-induced immune impairment", "Combats heat stress, ensuring overall health and productivity"],
    usage_info: ":\nFEED INCLUSION RATE:\nTo be mixed with drinking water or with feed\nSheep and Goats: 5 gm/animal/day for 3-5 days\nCalves: 10 g/animal/day for 3-5 days\nCattle, Camel & Horse: 20-30gm/animal/day\nfor 3-5 days\nPoultry: 1 Kg per tonne of feed or 1 gm in 2 litres\nof water for 3-5 days (In case of severe diarrhoea\nand threatened dehydration, dose should be doubled)",
    presentation: "3 x 1 Kg",
    pack_size: "3 x 1 Kg",
  },
  {
    name: "RevitoNex",
    category: "Miscellaneous Supplements",
    description: "high energy supplement for pre and postcalving period",
    features: ["Fulfills energy requirements, particularly during lactation, gestation, and the peri-partum period", "Prevents the formation of ketone bodies", "Enhances ruminal fermentation", "Addresses energy deficiencies and negative energy balance during critical periods"],
    usage_info: ":\nDOSE INTAKE LEVELS:\nVia Oral route\nCattle: 200 ml per day for the first two days,\nfollowed by 100 ml daily for the next two days\nSheep: In reducing the risk of Ketosis: 20 ml\nper day for 15 days before and after lambing\nIn recovery: 50 ml for 3 to 5 days in the last\n6 weeks before and 3 weeks after lambing",
    presentation: "1 Liter",
    pack_size: "1 Liter",
  },
  {
    name: "MOS Nex",
    category: "Miscellaneous Supplements",
    description: "An advanced gut health formulation enriched with MOS and -glucans",
    features: ["Effectively binds pathogenic enteric bacteria such as Salmonella spp. and Escherichia coli", "Promotes the growth and metabolic activity of beneficial gut microflora in the gastrointestinal tract", "Enhance nutrient uptake and absorption efficiency", "Acts as an immune modulator", "Improves feed efficiency and growth performance", "Helps lower mortality rates"],
    usage_info: "BENEFITS:\nDOSAGE:\nPoultry: 0.5 - 1.0 kg/MT\nSwine and ruminant: 1.0 - 2.0 kg/MT",
    presentation: "25 Kg",
    pack_size: "25 Kg",
  },
  {
    name: "EggoNex",
    category: "Egg Quality Enhancer",
    description: "Egg Quality Enhancer",
    features: ["Supports the mineralization of bone tissue", "Improves the quality of eggshells", "Reduces the incidence of cracked egg", "Helps in preventing osteomalacia"],
    usage_info: ":\nDOSE INTAKE LEVELS:\nPoultry: 1 ml per liter of drinking water\nOr as recommended by Nutritionist/\nVeterinarian",
    presentation: "1 Liter",
    pack_size: "1 Liter",
  },
  {
    name: "Scour Zil",
    category: "Antidiarrheal Supplements",
    description: "An effective supplement to control and counter scours in new born",
    features: ["To deliver essential minerals for specific animals", "An effective supplement to address and prevent scours in livestock"],
    usage_info: "DOSE INTAKE LEVELS:\nPut the bottle in the mouth of animal,\nwhile making upside down.\nEach spray is 1 ml\nLamb/Kid: 3 ml (3 pumps) twice a day\nCalves: 5 ml (5 pumps) twice a day\nYoung Camels: 10 ml (10 pumps)",
    presentation: "200 ml",
    pack_size: "200 ml",
  },
  {
    name: "WormGard Pet Tabs",
    category: "Pet Supplements",
    description: "All-inclusive DEWORMER for dogs with triple-action formula",
    features: [],
    usage_info: "INDICATION / USES:\nWormGard Pet Tabs should be\nused for the treatment against\nintestinal worms in Dogs, namely:\nRoundworms, Tapeworms,\nHookworms, Whipworms\nDOSE INTAKE LEVEL:\n1 tablet / 10 kg body weight for\nbest results two oral doses, two\nweeks apart\nor as directed by Veterinarian",
    presentation: "1 X 10 Tablets",
    pack_size: "1 X 10 Tablets",
  },
  {
    name: "FiproNex Pro Spot-on",
    category: "Pet Supplements",
    description: "For treating & managing parasitic infections on the skin",
    features: [],
    usage_info: "INDICATION / USES:\nFirproNex Pro Spot-on solution\nis designed to manage & treat\nthe skin infestations such as\nlice, fleas, and ticks\nDIRECTION FOR USE:\n1 pipette (unit pack) is a\n1.34 ml pipette for 10-20 kg dogs\ncomplete dose for\n2.68 ml pipette for 20-40 kg dogs\n4.02 ml pipette for 40 kg dogs\ncorresponding body weight",
    presentation: "0.67 ml pipette for 2-10 kg dogs",
    pack_size: "0.67 ml pipette for 2-10 kg dogs",
  },
  {
    name: "PetCleanse Shampoo",
    category: "Pet Supplements",
    description: "A therapeutic shampoo formulated to address external infestations in dogs",
    features: [],
    usage_info: "INDICATION / USES:\nThis medicated shampoo targets\nresistant ectoparasites including\nlice, fleas, and skin\nDIRECTION FOR USE:\nApply the shampoo liberally to\nwork up a creamy-rich lather.\nAllow it to remain and coat for\ngood 5 to 10 minutes & rinse\nthoroughly with clean water.\nThis shampoo can be used in\nall Dogs, except nursing bitches\nand pups under 3 months of age.",
    presentation: "200 ml",
    pack_size: "200 ml",
  },
  {
    name: "EpiDermix Pet Lotion",
    category: "Pet Supplements",
    description: "A multi-purpose antibiotic topical lotion",
    features: [],
    usage_info: "INDICATION / USES:\nThis lotion addresses different\nskin-related problems like\nEczematous dermatitis occurring\ndue to fungi & bacterial infections\nalong with other issues such as\nallergic dermatitis, pyoderma,\nringworm, pruritis, hot spots,\nwounds, yeast infections, folliculitis,\nand intertrigo.\nDIRECTION FOR USE:\nApply topically after cleaning\nof the affected area or wound\nfor 3-4 times a day",
    presentation: "100 ml, 30 ml",
    pack_size: "100 ml, 30 ml",
  },
  {
    name: "MicoNex Pro Pet Shampoo",
    category: "Pet Supplements",
    description: "Optimal Care for Smooth, Comforted & Healthy Skin",
    features: ["Two-in-One Solution: Integrates the antifungal efficacy of miconazole with potent antimicrobial benefits", "Multi-purpose care: Tackles a variety of skin concerns, including fungal, bacterial, and conditions related to skin irritation.", "Rapid Calming action: Delivers quick relief from itching and inflammation or instant comfort.", "Recurrence Control: Effectively lowers the likelihood of reinfection."],
    usage_info: "INDICATION / USES:\nDIRECTIONS FOR USE:\nWet your pet's coat thoroughly with\nlukewarm water. Apply a generous\namount of the shampoo & work into\na rich lather. Massage gently into the\ncoat & skin, ensuring even coverage.\nLeave the shampoo on the skin for\n5-10 minutes for optimal effectiveness.\nRinse thoroughly with water & repeat if necessary.",
    presentation: "200 ml",
    pack_size: "200 ml",
  },
  {
    name: "OtiCarePet Drops",
    category: "Pet Supplements",
    description: "Complete ear care: Long-term solution for all ear infections",
    features: [],
    usage_info: "INDICATION / USES:\nThese ear drops work against\nacute and chronic otitis media\nperpetuated by bacteria and/or\nfungi, yeast infections like\nmalassezia, pachydermatis,\notalgia (ear pain), otorrhoea,\nsevere pruritis\nDIRECTION FOR USE:\nAdminister liberally 8-10 drops\nin each affected ear twice daily.",
    presentation: "15 ml",
    pack_size: "15 ml",
  },
  {
    name: "AminoNex Pet",
    category: "Pet Supplements",
    description: "Advanced formula with DHA supplement for dogs & cats",
    features: ["Proper growth & development in growing & active pet", "Proper physical growth and tissue repair", "Growth & development of nervous system in puppies & kitten", "Promote vitality & strengthen dogs & cats physical condition", "Nutritional deficiency disorders", "Healthy & lustrous hair coat"],
    usage_info: "DOSE INTAKE LEVEL:\nUse AminoNex Pet Tabs according to body\nweight prior to feeding\nDOGS\n:\nPuppy below 5 kg: \u00bc  tablet twice daily\nUp to 10 kg: 1 tablet daily\nFrom 10-20 kg: 1 to 2 tablets daily\nAbove 20 kg: 2 to 3 tablets daily\nCATS\n:\nUpto 5 kg: \u00bd  tablet\nAbove 5 kg: 1 tablet daily",
    presentation: "60 Tablets",
    pack_size: "60 Tablets",
  },
  {
    name: "AminoNex Pet Liquid",
    category: "Pet Supplements",
    description: "Multi-Vitamin and Amino Acid Formula",
    features: ["Boosting immunity and vitality.", "Ensuring healthy development."],
    usage_info: "DOSE INTAKE LEVEL:\nDogs and Cats: 0.5 ml/kg as per b.wt\ntwice daily\nPregnant and Lactating Dogs, Cats and\ntheir Young ones: 2 ml/3 kg as per b.wt\ntwice daily\nBirds: 0.2 ml/bird twice daily (Considering\nb.wt of 500 g per bird)\nCan be mixed in feed/water as per feeding\nschedule and recommendation of Veterinarian",
    presentation: "200 ml",
    pack_size: "200 ml",
  },
  {
    name: "CalciNex Pet",
    category: "Pet Supplements",
    description: "Calcium & Phosphorus Supplements for Dog & Cats with Zn & Mg.",
    features: ["Supports bone development in growing puppies", "Aids in physical growth and tissue repair", "Beneficial for pregnant and lactating animals", "Promotes the healing of fractures"],
    usage_info: "DOSE INTAKE LEVEL:\nUse CalciNex Pet according to body\nweight prior to feeding\nPuppy & Kitten: \u00bd Tablet twice daily\nAdult: 1 Tablet per 10 kg. Body weight in\ndivided doses",
    presentation: "60 Tablets",
    pack_size: "60 Tablets",
  },
  {
    name: "ProbioNex Pet Care",
    category: "Pet Supplements",
    description: "High-Performance Synbiotic Digestive Aid for Pets",
    features: ["Promote a healthy gut microbiome and digestive function", "Help combat gastrointestinal infections caused by E. coli", "Shorten digestion time by promoting the release of Amylase, Protease, Lipase, and Phytase", "Reduce abdominal discomfort caused by gas", "High antioxidant capacity", "Detoxifies the body", "Stimulates T-cell response and supports immune health", "Improves nutrient absorption for better health"],
    usage_info: "BENEFITS:\nFEED INCLUSION RATE:\nPuppy: 1 g Twice daily (\u00bc spoon)\nCurative dosage:\nPuppy: 1-2 g Twice daily (\u00bc to \u00bd spoon)\nSmall breed Dogs: 3-4 g daily (3/4 to 1 spoon)\nMedium breed: 4-5 g daily (1 to 1 \u00bc spoon)\nLarge breed: 6-8 g daily (1 \u00bd to 2 spoon)\nCats: 1-2 g Twice daily (\u00bc to \u00bd spoon)",
    presentation: "100 g",
    pack_size: "100 g",
  },
  {
    name: "RevitoNex Pet",
    category: "Pet Supplements",
    description: "Nourishing Formula for Improved Digestive System Development",
    features: ["Facilitates the development of the small intestine", "Improve immune defence through cellular and humoral enhancement", "Promotes even and steady growth", "Supports healthier growth and a radiant coat", "Prevention of diarrhoea-related diseases", "Supports liver healing and regeneration", "For efficient toxin absorption and binding"],
    usage_info: "BENEFITS:\nFEED INCLUSION RATE:\nPuppy Dog: 2 to 4 g daily\nAdult Dog: 4 to 8 g\nCats: 2 to 4 g",
    presentation: "100 g",
    pack_size: "100 g",
  },
  {
    name: "Liveron Pet",
    category: "Pet Supplements",
    description: "POWERFUL LIVER TONIC & APPETITE BOOSTER IMPROVES LIVER FUNCTION & FOOD INTAKE SYRUP",
    features: ["Assists in managing Ascites and Cirrhosis of the liver", "Supports recovery during Distemper and Parvovirus infections", "Acts as an adjuvant in the treatment of Canine and Feline Viral Hepatitis", "Provides supportive care alongside antibiotics and anti-parasitic treatments", "Aids in post-operative recovery as a complementary therapy"],
    usage_info: "DOSE INTAKE LEVELS:\nAdult Dogs/Cats: 10 ml twice daily (\u00bc spoon)\nPups & Small Breed Dogs: 2-5 ml twice daily\nKittens: 2-5 ml twice daily\nOr as directed by the Veterinary Doctor",
    presentation: "200 ml",
    pack_size: "200 ml",
  },
  {
    name: "ArthroNex Pet",
    category: "Pet Supplements",
    description: "Glucosamine, Chondroitin, MSM, EPA, and DHA-based supplement for joint and hip dysplasia care in dogs and cats",
    features: ["Helps preserve the integrity of cartilage, tendons, and ligaments in cases of hip dysplasia, arthritis, and joint issues", "Aids in stress management for animals"],
    usage_info: "RECOMMENDATION:\nFEED INCLUSION RATE:\nCANINE:\nAs treatment\nAs follow-up\n(gm/day for 8 to\n(gm/day for 3 to\n10 weeks)\n6 weeks)\nUp to 10 kg\n4 g (1 Scoop)\n2 g (\u00bd Scoop)\nFrom 10 kg to 20 kg\n6 g (1\u00bd Scoop)\n4 g (1 Scoop)\nAbove 20 kg\n8 g (2 Scoops)\n4 g (1 Scoop)\nFELINE:\nUp to 5 kg\n2 g (1\u00bd Scoop)\nAlternate days\nAbove 5 kg\nAlternate days\n4 g (1 Scoop)",
    presentation: "120 g",
    pack_size: "120 g",
  },
  {
    name: "OmegaFur Pet Tabs",
    category: "Pet Supplements",
    description: "Multivitamin & Omega-Powered Supplement for Pet Skin and Coat Health",
    features: ["Enhanced skin softness and shine", "Helps manage dandruff", "Reduces the risk of skin allergies", "Calms itching sensations", "Promotes proper skin function and coat condition"],
    usage_info: "BENEFITS:\nDOSE INTAKE LEVELS:\nUpto 20 kg body weight: 1-2 tablets\nMore than 20 kg body weight:\n2-4 tablets\nOR as advised by Veterinarian",
    presentation: "50 Tablets",
    pack_size: "50 Tablets",
  },
  {
    name: "BioCleanse Shampoo",
    category: "Pet Supplements",
    description: "Eradication of external parasites BioCleanse Shampoo, a botanical research-based product, is expertly crafted for pets using natural ingredients such as Azadirachta indica, Cedrus deodara, Cocos nucifera, Pongamia pinnata, and Premna integrifolia, renowned for their effectiveness in preventing and controlling ectoparasitic infestations like ticks, fleas, and lice.",
    features: [],
    usage_info: "DIRECTIONS OF USE:\nApply some amount of the shampoo\non wet body coat. Avoid application\naround eyes & face. Massage well to\nrich lather. Let it soak on the skin for\n5-10 minutes. Rinse thoroughly.\nRepeat if necessary. Towel dry, brush\n& comb completely.",
    presentation: "275 ml",
    pack_size: "275 ml",
  },
  {
    name: "GlowNex Shampoo",
    category: "Pet Supplements",
    description: "Advanced formula with DHA supplement for dogs & cats GLOWNEX CONDITIONING SHAMPOO is expertly formulated with unique botanical extracts to cater to your dog's fur needs.",
    features: ["Nourishes, softens, and moisturizes the coat.", "Protects against harmful UV rays.", "Leaves a lasting, pleasant fragrance."],
    usage_info: "HOW TO USE:\nThoroughly wet the dog with lukewarm water.\nApply an adequate amount of shampoo and\nmassage gently to create a rich lather. Rinse\nthoroughly with water. Dry with a towel,\nthen brush and comb.",
    presentation: "300 ml",
    pack_size: "300 ml",
  },
  {
    name: "PhytoZil Pet Shampoo",
    category: "Pet Supplements",
    description: "Botanical nourishment & conditioning",
    features: ["A herbal shampoo with balanced pH levels", "Specifically created for pets with different coat types", "Gentle yet effective at cleansing and nourishing", "Includes Shikakai, Aritha, and Aloe vera for added benefit", "Suitable for daily use"],
    usage_info: "BENEFITS:\nDIRECTIONS OF USE:\nApply some amount of the shampoo\non wet body coat. Avoid application\naround eyes & face. Massage well to\nrich lather. Let it soak on the skin for\n5-10 minutes. Rinse thoroughly.\nRepeat if necessary. Towel dry, brush\n& comb completely.",
    presentation: "275 ml",
    pack_size: "275 ml",
  },
  {
    name: "WoundZil",
    category: "Pet Supplements",
    description: "100% natural animal healing spray",
    features: ["Efficient and simple to administer.", "This economical pack includes an extension tube for deep penetration.", "The aerosol format ensures thorough penetration into all exposed tissue cells."],
    usage_info: "DIRECTION FOR USE:\nExternal Use. Spray after Cleaning and\nTrimming to cover the wound, once a\nday depending on the case.",
    presentation: "100 ml",
    pack_size: "100 ml",
  },
  {
    name: "AquaNex Pro",
    category: "Aqua Products",
    description: "Soil & Water Probiotics: Shrimp, Prawn & Fish",
    features: ["Enhances the disease resistance of larvae", "Boosts pathogen resistance", "Improves digestion and feed conversion ratio (FCR)", "Allows for increased stocking density in the same LR tank during a cycle", "Reduces the need for antibiotics and chemicals in tanks", "Accelerates growth, enabling earlier harvest", "Facilitates the breakdown of organic waste and leftover feed", "Supports the growth of healthy plankton."],
    usage_info: ":\nFEED INCLUSION RATE:\n200 grams per Ton of feed\nor as recommended by Aquaculture\nConsutlant",
    presentation: "1 KG",
    pack_size: "1 KG",
  },
  {
    name: "AquaNex Oxy",
    category: "Aqua Products",
    description: "Dissolved Oxygen Improver in Aqua ponds",
    features: ["Fast development of dissolved oxygen"],
    usage_info: "FEED INCLUSION RATE:\n1 mt water depth/2 to 3 weeks\nPowder: 2 to 4 Kg/ha\nGranules: 2 to 4 Kg/ha\nTablet: 1 to 2 Kg/ha",
    presentation: "1 KG",
    pack_size: "1 KG",
  },
  {
    name: "AquaNex Extra",
    category: "Aqua Products",
    description: "For Fast growth and more body weights",
    features: ["For increasing body weight"],
    usage_info: ":\nFEED INCLUSION RATE:\nPrawn & Fish Feed:\nDuring Culture: 10 g/Kg of pellets\nDuring Feed Preparation:\n2-5 kg/metric ton of Feed",
    presentation: "1 KG",
    pack_size: "1 KG",
  },
  {
    name: "AquaNex Tonic",
    category: "Aqua Products",
    description: "Liver tonic and growth promoter",
    features: ["Prevents and controls all types of liver diseases/yellow liver (Jaundice Disease) and growth promoter in Fishes"],
    usage_info: "DOSE INTAKE LEVELS:\n1 to 5 ml per kg of feed for\n3 to 7 days\ndepending on need and condition\nOr as directed by Aqua Nutritionist",
    presentation: "1 Liter",
    pack_size: "1 Liter",
  },
  {
    name: "AquaNex Licid H",
    category: "Aqua Products",
    description: "Unique Blend of Phytoactives Liquid for Aquatic Ectoparasites",
    features: ["Targets and controls both adult and spore stages of Fish Lice (Argulus) in cultured fish", "Disrupts the parasite's life cycle during the reproductive phase, effectively controlling Argulus", "Reduces redness, inflammation, and raised scales on the fish's body and fins", "Heals swelling and open wounds in fish", "Has no impact on pond water quality parameters", "Treats ulcers and open wounds while promoting quick repair of damaged or ragged fins and tails"],
    usage_info: "DOSE INTAKE LEVELS:\nDay Zero \u2013 Through Feed: \u2013, In Pond: 1 liter/acre\nDay 2nd \u2013 Through Feed: 100 ml/ton, In Pond: 100 ml/ton\nDay 15th (re-infestation of Lice is seen) \u2013 Through Feed: 100 ml/ton, In Pond: 500 ml/acre\nDay 15th (re-infestation of Lice is not seen, repeat once on 17th day) \u2013 Through Feed: 100 ml/ton, In Pond: \u2013",
    presentation: "1 Liter",
    pack_size: "1 Liter",
  },
];
